### ISSUE TITLE
Regexp for extension validation breaking

### ISSUE THREAD

**Issue by zakeri** [TryGhost/Ghost-Storage-Base#2]
Hi guys, I have a problem with your code in BaseStorage.js for validating file extenstion:

> `if (!ext.match(/.\d/))`

Since I am working on a change in Ghost to accept mp3 files for upload, on duplicate filenames it is generating "sample.mp3-1" instead of "sample-1.mp3". Of course, I could unblock myself by using a forked and renamed package but shouldn't we make this regexp more meaningful? Like `/\.\d+$/` if you meant to exclude .1 extensions?

**Comment by kirrg001** [comment]
@zakeri Hey! 

Sure thing, a PR is welcome 👍

**Comment by zakeri** [comment]
Thanks, I just posted the PR.

**Comment by zakeri** [comment]
@kirrg001 Dear Katharina, is the merge going to happen anytime soon?

**Comment by ErisDS** [comment]
Hey there @zakeri your PR was only made 3 days ago, and it's the weekend - we're only human

**Comment by zakeri** [comment]
@ErisDS :)

**Comment by ErisDS** [comment]
I believe this was (finally) fixed here: https://github.com/TryGhost/Ghost-Storage-Base/commit/320d87a35f3cb5b3b7ddecfad99497e0405a4b5a
