### ISSUE TITLE
Docs and usage of exists() are different

### ISSUE THREAD

**Issue by iamakulov** [TryGhost/Ghost-Storage-Base#4]
In [the docs for custom storage modules](https://docs.ghost.org/docs/using-a-custom-storage-module#section--exists-), it’s stated that the `exists()` function accepts only a single filename argument:

![image](https://user-images.githubusercontent.com/2953267/35755718-6b7a2a02-0879-11e8-904c-2f7de2777af2.png)

However, the StorageBase implementation differs from the docs – it passes two parameters into the method:

https://github.com/TryGhost/Ghost-Storage-Base/blob/18527f5b8a2c03361ce41539004aba038e41bf83/BaseStorage.js#L41

Because of this, some adapters (e.g. [`ghost-storage-adapter-s3`](https://github.com/colinmeinke/ghost-storage-adapter-s3) – ref https://github.com/colinmeinke/ghost-storage-adapter-s3/pull/28) expect to receive a full filename and fail to check if the uploaded file already exists. I don’t know how many modules are affected by this.

Is the problem in the docs or in the implementation? Which of them should we change?

**Comment by kirrg001** [comment]
@iamakulov Hey!

The base storage adapter forwards two properties: **fileName and targetDir**. 

But the `targetDir` property can be empty. The storage adapter has to deal with that.

I'll update the docs.

**Comment by iamakulov** [comment]
Thanks!
