### ISSUE TITLE
Is there any breaking change in v1.0.0

### ISSUE THREAD

**Issue by tranvansang** [TryGhost/Ghost-Storage-Base#54]
I've found that the package has been upgraded to v1.0.0.

Is there is any breaking change in this version? Please correct me if I miss something.

PS: I am maintaining the package https://github.com/tranvansang/s3-ghost. I am going to update it to support additional flag: custom endpoint: DO spaces,... and found that ghost-storage-base updated with to a new major version.

**Comment by ErisDS** [comment]
No, there are minor changes only. The version bump reflects the maturity of the module.
